spring:
  application:
    name: company
  datasource:
    url: jdbc:mysql://localhost:3306/employeesdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: your_password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Dima
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: dima-rest-api
      principle-attribute: preferred_username

server:
  port: 8081